name: Generate GitHub Stats SVG
on:
  schedule:
    - cron: "0 */6 * * *"
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: jstrieb/github-stats@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
